server:
  port: 9090

spring:
  datasource:
    name: security
#    url: jdbc:mysql://ip:port/database?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 300000
#      validation-timeout:
#      connection-test-query: SELECT 1 FROM DUAL

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #hibernate的 格式化sql

  redis:
    host:
    port: 6379
    password:
    database: 0
    lettuce:
      shutdown-timeout: 100ms # 关闭超时时间
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接

#  session:
#    store-type: none #有默认配置
